#!/bin/sh

iptables -t nat -A PREROUTING -p tcp --dport $1 -j DNAT --to $2:$3  > /dev/null 2>&1 
iptables -t nat -A PREROUTING -p udp --dport $1 -j DNAT --to $2:$3  > /dev/null 2>&1 


iptables -t nat -L -n 2> /dev/null
